# Generated by Django 5.0.6 on 2024-07-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='Age',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='designer',
            new_name='name',
        ),
    ]
